# Makefile sample
# make speak .... echoes "hello world!" on screen

# Variables are defined using ?= 
NORMAL_ENV_VAR ?= "hello world!"


# Makefile consists of tab, disallows spaces, better to comment out expand tab lines 
# in ~/.vimrc
speak: 
	echo $(NORMAL_ENV_VAR)

